Host alpha
  HostName alpha.example.com
  User deploy
  # purple:vault-ssh ssh-client-signer/sign/my-role
  CertificateFile ~/.purple/certs/alpha-cert.pub

Host beta
  HostName beta.example.com
  User root
  # purple:tags prod,eu-west
