Include ~/.ssh/config.d/*.conf
Include /etc/ssh/ssh_config

Host alpha
  HostName 10.0.0.1
  # purple:vault-ssh ssh-client-signer/sign/role-a
  CertificateFile ~/.purple/certs/alpha-cert.pub

Host beta
  HostName 10.0.0.2
  IdentityFile ~/.ssh/beta_ed25519
