Host *
  ServerAliveInterval 60
  ForwardAgent no

Host *.example.com
  User deploy
  IdentityFile ~/.ssh/example_ed25519

Host alpha
  HostName alpha.example.com
  # purple:vault-ssh ssh-client-signer/sign/alpha-role
  CertificateFile ~/.purple/certs/alpha-cert.pub

Host beta
  HostName beta.example.com
